// Generated from Tatoeba downloads language selector data.
// Source: https://tatoeba.org/en/downloads

export const SUPPORTED_LANGUAGES = {
  abq: "Abaza",
  abk: "Abkhaz",
  ady: "Adyghe",
  afh: "Afrihili",
  afr: "Afrikaans",
  ain: "Ainu",
  akl: "Aklanon",
  sqi: "Albanian",
  arq: "Algerian Arabic",
  amh: "Amharic",
  grc: "Ancient Greek",
  hbo: "Ancient Hebrew",
  njo: "Ao Naga",
  ara: "Arabic",
  arg: "Aragonese",
  asm: "Assamese",
  aii: "Assyrian Neo-Aramaic",
  ast: "Asturian",
  ava: "Avar",
  awa: "Awadhi",
  aym: "Aymara",
  aze: "Azerbaijani",
  ban: "Balinese",
  bal: "Baluchi",
  bam: "Bambara",
  bjn: "Banjar",
  bak: "Bashkir",
  eus: "Basque",
  bar: "Bavarian",
  bvy: "Baybayanon",
  bel: "Belarusian",
  ben: "Bengali",
  ber: "Berber",
  bom: "Berom",
  bho: "Bhojpuri",
  bis: "Bislama",
  brx: "Bodo",
  bos: "Bosnian",
  bre: "Breton",
  bzt: "Brithenig",
  bul: "Bulgarian",
  mya: "Burmese",
  bua: "Buryat",
  yue: "Cantonese",
  cat: "Catalan",
  cay: "Cayuga",
  ceb: "Cebuano",
  bcl: "Central Bikol",
  dtp: "Central Dusun",
  nch: "Central Huasteca Nahuatl",
  knc: "Central Kanuri",
  ckb: "Central Kurdish (Soranî)",
  cmo: "Central Mnong",
  chg: "Chagatai",
  cha: "Chamorro",
  cbk: "Chavacano",
  che: "Chechen",
  chr: "Cherokee",
  cpi: "Chinese Pidgin English",
  chn: "Chinook Jargon",
  nya: "Chinyanja",
  cho: "Choctaw",
  ckt: "Chukchi",
  chv: "Chuvash",
  kzj: "Coastal Kadazan",
  swc: "Congo Swahili",
  cor: "Cornish",
  cos: "Corsican",
  crh: "Crimean Tatar",
  hrv: "Croatian",
  cyo: "Cuyonon",
  cycl: "CycL",
  ces: "Czech",
  dan: "Danish",
  dar: "Dargwa",
  div: "Dhivehi",
  drt: "Drents",
  dng: "Dungan",
  nld: "Dutch",
  dws: "Dutton World Speedwords",
  hye: "Eastern Armenian",
  arz: "Egyptian Arabic",
  egl: "Emilian",
  eng: "English",
  emx: "Erromintxela",
  myv: "Erzya",
  epo: "Esperanto",
  est: "Estonian",
  evn: "Evenki",
  ewe: "Ewe",
  ext: "Extremaduran",
  fao: "Faroese",
  hif: "Fiji Hindi",
  fij: "Fijian",
  fin: "Finnish",
  fra: "French",
  fry: "Frisian",
  fur: "Friulian",
  gaa: "Ga",
  gag: "Gagauz",
  glg: "Galician",
  gan: "Gan Chinese",
  gbm: "Garhwali",
  kat: "Georgian",
  deu: "German",
  aln: "Gheg Albanian",
  gil: "Gilbertese",
  got: "Gothic",
  ell: "Greek",
  kal: "Greenlandic",
  gos: "Gronings",
  gcf: "Guadeloupean Creole French",
  grn: "Guarani",
  ngu: "Guerrero Nahuatl",
  guj: "Gujarati",
  afb: "Gulf Arabic",
  guw: "Gun",
  hat: "Haitian Creole",
  hak: "Hakka Chinese",
  hau: "Hausa",
  haw: "Hawaiian",
  heb: "Hebrew",
  hil: "Hiligaynon",
  mrj: "Hill Mari",
  hin: "Hindi",
  mik: "Hitchiti",
  mww: "Hmong Daw (White)",
  hnj: "Hmong Njua (Green)",
  hoc: "Ho",
  hun: "Hungarian",
  hrx: "Hunsrik",
  iba: "Iban",
  isl: "Icelandic",
  ido: "Ido",
  ibo: "Igbo",
  ilo: "Ilocano",
  ind: "Indonesian",
  izh: "Ingrian",
  inh: "Ingush",
  igs: "Interglossa",
  ina: "Interlingua",
  ile: "Interlingue",
  isv: "Interslavic",
  ike: "Inuktitut",
  acm: "Iraqi Arabic",
  gle: "Irish",
  tts: "Isan",
  ita: "Italian",
  jam: "Jamaican Patois",
  jpn: "Japanese",
  jav: "Javanese",
  tmr: "Jewish Babylonian Aramaic",
  jpa: "Jewish Palestinian Aramaic",
  cjy: "Jin Chinese",
  jdt: "Juhuri (Judeo-Tat)",
  quc: "K'iche'",
  kbd: "Kabardian",
  kab: "Kabyle",
  xal: "Kalmyk",
  kam: "Kamba",
  kan: "Kannada",
  pam: "Kapampangan",
  krc: "Karachay-Balkar",
  kaa: "Karakalpak",
  xqa: "Karakhanid",
  krl: "Karelian",
  kas: "Kashmiri",
  csb: "Kashubian",
  kaz: "Kazakh",
  kek: "Kekchi (Q'eqchi')",
  mfa: "Kelantan-Pattani Malay",
  kxi: "Keningau Murut",
  kjh: "Khakas",
  klj: "Khalaj",
  kha: "Khasi",
  khm: "Khmer",
  kin: "Kinyarwanda",
  run: "Kirundi",
  tlh: "Klingon",
  ksh: "Kölsch",
  koi: "Komi-Permyak",
  kpv: "Komi-Zyrian",
  gom: "Konkani (Goan)",
  kor: "Korean",
  avk: "Kotava",
  kum: "Kumyk",
  fkv: "Kven Finnish",
  kir: "Kyrgyz",
  ldn: "Láadan",
  lld: "Ladin",
  lad: "Ladino",
  lbe: "Lak",
  lkt: "Lakota",
  lao: "Lao",
  ltg: "Latgalian",
  lat: "Latin",
  lvs: "Latvian",
  lzz: "Laz",
  lez: "Lezgi",
  ayl: "Libyan Arabic",
  lij: "Ligurian",
  lim: "Limburgish",
  lin: "Lingala",
  lfn: "Lingua Franca Nova",
  lzh: "Literary Chinese",
  lit: "Lithuanian",
  liv: "Livonian",
  jbo: "Lojban",
  lmo: "Lombard",
  lou: "Louisiana Creole",
  nds: "Low German (Low Saxon)",
  dsb: "Lower Sorbian",
  lug: "Luganda",
  lut: "Lushootseed",
  ltz: "Luxembourgish",
  mkd: "Macedonian",
  mad: "Madurese",
  bfz: "Mahasu Pahari",
  mai: "Maithili",
  mlg: "Malagasy",
  zsm: "Malay",
  zlm: "Malay (Vernacular)",
  mal: "Malayalam",
  mlt: "Maltese",
  mgm: "Mambae",
  mnc: "Manchu",
  mdr: "Mandar",
  cmn: "Mandarin Chinese",
  glv: "Manx",
  mri: "Maori",
  arn: "Mapuche",
  mar: "Marathi",
  mah: "Marshallese",
  mhr: "Meadow Mari",
  mni: "Meitei",
  mic: "Mi'kmaq",
  enm: "Middle English",
  frm: "Middle French",
  pal: "Middle Persian (Pahlavi)",
  nan: "Min Nan Chinese",
  min: "Minangkabau",
  xmf: "Mingrelian",
  mwl: "Mirandese",
  moh: "Mohawk",
  mdf: "Moksha",
  mnw: "Mon",
  mon: "Mongolian",
  mnr: "Mono (USA)",
  mfe: "Morisyen",
  ary: "Moroccan Arabic",
  mus: "Muskogee (Creek)",
  nst: "Naga (Tangshang)",
  nah: "Nahuatl",
  nnb: "Nande",
  nau: "Nauruan",
  nav: "Navajo",
  nap: "Neapolitan",
  npi: "Nepali",
  new: "Newari",
  ngt: "Ngeq ",
  fuv: "Nigerian Fulfulde",
  niu: "Niuean",
  nog: "Nogai",
  frr: "North Frisian",
  apc: "North Levantine Arabic",
  max: "North Moluccan Malay",
  hdn: "Northern Haida",
  kmr: "Northern Kurdish (Kurmancî)",
  sme: "Northern Sami",
  kiu: "Northern Zaza (Kirmanjki)",
  nob: "Norwegian Bokmål",
  nno: "Norwegian Nynorsk",
  nov: "Novial",
  nus: "Nuer",
  iii: "Nuosu",
  nys: "Nyungar",
  ood: "O'odham",
  oci: "Occitan",
  ori: "Odia (Oriya)",
  oji: "Ojibwe",
  ryu: "Okinawan",
  oar: "Old Aramaic",
  orv: "Old East Slavic",
  ang: "Old English",
  fro: "Old French",
  ofs: "Old Frisian",
  non: "Old Norse",
  prg: "Old Prussian",
  osx: "Old Saxon",
  osp: "Old Spanish",
  otk: "Old Turkish",
  nlv: "Orizaba Nahuatl",
  oss: "Ossetian",
  ota: "Ottoman Turkish",
  pfl: "Palatine German",
  pau: "Palauan",
  pli: "Pali",
  pag: "Pangasinan",
  pap: "Papiamento",
  pus: "Pashto",
  pdc: "Pennsylvania German",
  pes: "Persian",
  phn: "Phoenician",
  pcd: "Picard",
  pms: "Piedmontese",
  ppl: "Pipil",
  crk: "Plains Cree",
  pol: "Polish",
  por: "Portuguese",
  fuc: "Pulaar",
  pan: "Punjabi (Eastern)",
  pnb: "Punjabi (Western)",
  qxq: "Qashqai",
  que: "Quechua",
  qya: "Quenya",
  rap: "Rapa Nui",
  rel: "Rendille",
  rhg: "Rohingya",
  rom: "Romani",
  ron: "Romanian",
  roh: "Romansh",
  rus: "Russian",
  rue: "Rusyn",
  smo: "Samoan",
  sgs: "Samogitian",
  sag: "Sango",
  san: "Sanskrit",
  sat: "Santali",
  skr: "Saraiki",
  srd: "Sardinian",
  stq: "Saterland Frisian",
  sco: "Scots",
  gla: "Scottish Gaelic",
  srp: "Serbian",
  tsn: "Setswana",
  crs: "Seychellois Creole",
  wuu: "Shanghainese",
  sna: "Shona",
  shs: "Shuswap",
  scn: "Sicilian",
  szl: "Silesian",
  sjn: "Sindarin",
  snd: "Sindhi",
  sin: "Sinhala",
  slk: "Slovak",
  slv: "Slovenian",
  som: "Somali",
  ajp: "South Levantine Arabic",
  alt: "Southern Altai",
  hax: "Southern Haida",
  sdh: "Southern Kurdish",
  sma: "Southern Sami",
  sot: "Southern Sotho",
  laa: "Southern Subanen",
  diq: "Southern Zaza (Dimli)",
  spa: "Spanish",
  srn: "Sranan Tongo",
  zgh: "Standard Moroccan Tamazight",
  sux: "Sumerian",
  sun: "Sundanese",
  sva: "Svan",
  swg: "Swabian",
  swh: "Swahili",
  ssw: "Swazi",
  swe: "Swedish",
  gsw: "Swiss German",
  syl: "Sylheti",
  syc: "Syriac",
  shy: "Tachawit",
  mvv: "Tagal Murut",
  tgl: "Tagalog",
  thv: "Tahaggart Tamahaq",
  tah: "Tahitian",
  tgk: "Tajik",
  tzl: "Talossan",
  tly: "Talysh",
  tam: "Tamil",
  rif: "Tarifit",
  shi: "Tashelhit",
  tat: "Tatar",
  tel: "Telugu",
  tmw: "Temuan",
  tet: "Tetun",
  tha: "Thai",
  bod: "Tibetan",
  tig: "Tigre",
  tir: "Tigrinya",
  tpi: "Tok Pisin",
  tkl: "Tokelauan",
  tok: "Toki Pona",
  toi: "Tonga (Zambezi)",
  ton: "Tongan",
  tso: "Tsonga",
  tum: "Tumbuka",
  tpn: "Tupinambá",
  tur: "Turkish",
  tuk: "Turkmen",
  tvl: "Tuvaluan",
  tyv: "Tuvinian",
  aoz: "Uab Meto",
  udm: "Udmurt",
  ukr: "Ukrainian",
  umb: "Umbundu",
  hsb: "Upper Sorbian",
  urd: "Urdu",
  urh: "Urhobo",
  uig: "Uyghur",
  uzb: "Uzbek",
  vec: "Venetian",
  vep: "Veps",
  vie: "Vietnamese",
  vol: "Volapük",
  vro: "Võro",
  wln: "Walloon",
  war: "Waray",
  guc: "Wayuu",
  cym: "Welsh",
  gaz: "West-Central Oromo",
  hyw: "Western Armenian",
  wol: "Wolof",
  xho: "Xhosa",
  hsn: "Xiang Chinese",
  sah: "Yakut",
  yid: "Yiddish",
  yor: "Yoruba",
  yua: "Yucatec Maya",
  zza: "Zaza",
  zea: "Zeelandic",
  zul: "Zulu",
} as const;

export type SupportedLanguageCode = keyof typeof SUPPORTED_LANGUAGES;
export type SupportedLanguageName =
  (typeof SUPPORTED_LANGUAGES)[SupportedLanguageCode];

export const SUPPORTED_LANGUAGE_CODES = Object.keys(
  SUPPORTED_LANGUAGES,
) as SupportedLanguageCode[];

const SUPPORTED_LANGUAGE_CODE_SET = new Set<string>(SUPPORTED_LANGUAGE_CODES);

export function isSupportedLanguageCode(
  code: string,
): code is SupportedLanguageCode {
  return SUPPORTED_LANGUAGE_CODE_SET.has(code);
}
